### ISSUE TITLE
Fails to build with glibc 2.30

### ISSUE THREAD

**Issue by kraj** [thkukuk/libnss_nis#6]
```
| ../../git/src/nis-hosts.c:235:21: error: use of undeclared identifier 'RES_USE_INET6'
|                         ((_res.options & RES_USE_INET6) ? AF_INET6 : AF_INET),
|                                          ^
| ../../git/src/nis-hosts.c:236:21: error: use of undeclared identifier 'RES_USE_INET6'
|                         ((_res.options & RES_USE_INET6) ? AI_V4MAPPED : 0 ));
|                                          ^
| ../../git/src/nis-hosts.c:355:21: error: use of undeclared identifier 'RES_USE_INET6'
|                         ((_res.options & RES_USE_INET6) ? AI_V4MAPPED : 0));
|                                          ^
| ../../git/src/nis-hosts.c:363:22: error: use of undeclared identifier 'RES_USE_INET6'
|   if (_res.options & RES_USE_INET6)
|                      ^
| ../../git/src/nis-hosts.c:437:27: error: use of undeclared identifier 'RES_USE_INET6'
|                               ((_res.options & RES_USE_INET6)
|                                                ^
| 5 errors generated.
| make[2]: *** [Makefile:682: nis-hosts.lo] Error 1
```

**Comment by thkukuk** [comment]
3.1 should work again
